name: "Performance Benchmark"
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "*/45 * * * *"
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      placeholder:
        description: "placeholder, no effect"
        required: false

jobs:
  rerun:
    name: Throughput
    runs-on: [self-hosted, linux, gpu]
    strategy:
      max-parallel: 5
      matrix:
        model: ["resnet50"]
    steps:
      - name: Fix permissions
        if: matrix.test_suite != 'mac'
        run: |
          docker run --rm -v $PWD:/p -w /p busybox chmod -R o+w .
      - uses: actions/checkout@v2
      - name: Checkout OneFlow-Benchmark
        uses: actions/checkout@v2
        with:
          repository: Oneflow-Inc/OneFlow-Benchmark
          path: OneFlow-Benchmark
      - name: "Run benchmark"
        run: |
          set -x
          INSTALL_CMD="python3 -m pip install oneflow --user -f https://staging.oneflow.info/branch/master/cu102"
          container_name="perf-dog-run-id-${{ github.run_id }}-model-${{ matrix.model }}"
          echo "container_name=$container_name" >> $GITHUB_ENV
          docker run \
            --shm-size=8g --rm \
            --name $container_name \
            -w $PWD -v $PWD:$PWD \
            -v /dataset:/dataset -v /model_zoo:/model_zoo \
            -e ONEFLOW_BENCHMARK_DIR=${PWD}/OneFlow-Benchmark \
            oneflow-test:$USER \
            bash -c "$INSTALL_CMD && bash models/${{ matrix.model }}.sh"
      - name: Remove container
        if: always() && matrix.test_suite != 'mac'
        run: |
          docker rm -f ${container_name} || true
